title: MIT DEAL
email: deal-exec-2020@mit.edu
description: >- # this means to ignore newlines until "baseurl:"
  Discover Entrepreneurship and Leadership, a week-long program for
  MIT first-years students to learn of our campus's vast entrepreneurial
  opportunities and grow as future leaders.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mit-deal
instagram_username: mitdeal

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed